spring:
  application:
    name: to-do-list
  data:
    mongodb:
      username: root
      password: secret
      database: tasks-db
      port: 27017
      host: mongodb
  #      uri: mongodb://mongodb:27017/tasks-db
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none